name: Linux VPS (SSH) with Tailscale

on:
  workflow_dispatch:

jobs:
  secure-vps:
    runs-on: ubuntu-latest # ⬅️ CHANGE: Switched to Ubuntu (Linux) runner
    timeout-minutes: 3600

    steps:
      - name: Create VPS User with Secure Password
        run: |
          # 1. Generate a secure random password (16 characters)
          # Using tr and head for simple, fast password generation on Linux
          password=$(LC_ALL=C tr -dc 'A-Za-z0-9!@#$%^&*()_+=-' < /dev/urandom | head -c 16)
          username="vpsuser"
          
          # 2. Create the user and set their password
          sudo useradd -m -s /bin/bash $username
          echo "$username:$password" | sudo chpasswd
          
          # 3. Add user to the sudo group for root privileges
          sudo usermod -aG sudo $username
          
          # 4. Save credentials for later output
          echo "RDP_CREDS=User: $username | Password: $password" >> $GITHUB_ENV
          
          if ! id -u $username > /dev/null 2>&1; then
              echo "User creation failed"
              exit 1
          fi

      - name: Configure SSH and Firewall
        run: |
          # ⬅️ CHANGE: RDP steps removed, SSH is usually enabled on port 22.
          # 1. Ensure SSH server is installed and running
          sudo apt-get update
          sudo apt-get install -y openssh-server
          
          # 2. Allow password authentication (needed since we are not using SSH keys)
          sudo sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          
          # 3. Restart SSH service
          sudo service ssh restart
          
          # 4. Open port 22 on the internal firewall (if necessary, though GH runners are permissive)
          sudo ufw allow 22/tcp

      - name: Install Tailscale
        run: |
          # ⬅️ CHANGE: Linux (apt/curl) installation process
          sudo curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.no-arch.gpg | sudo dd of=/usr/share/keyrings/tailscale-archive-keyring.gpg
          sudo curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale.list | sudo dd of=/etc/apt/sources.list.d/tailscale.list
          sudo apt-get update
          sudo apt-get install -y tailscale

      - name: Establish Tailscale Connection
        run: |
          # Bring up Tailscale with the provided auth key
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$GITHUB_RUN_ID
          
          # Wait for Tailscale to assign an IP
          tsIP=""
          retries=0
          while [ -z "$tsIP" ] && [ $retries -lt 10 ]; do
              tsIP=$(sudo tailscale ip -4)
              sleep 5
              retries=$((retries+1))
          done
          
          if [ -z "$tsIP" ]; then
              echo "Tailscale IP not assigned. Exiting."
              exit 1
          fi
          echo "TAILSCALE_IP=$tsIP" >> $GITHUB_ENV

      - name: Verify SSH Accessibility
        run: |
          echo "Tailscale IP: $TAILSCALE_IP"
          
          # Simple check to see if SSH port (22) is reachable via the Tailscale IP
          if ! timeout 5 bash -c "</dev/tcp/$TAILSCALE_IP/22"; then
              echo "TCP connection to SSH port 22 failed"
              exit 1
          fi
          echo "SSH connectivity successful! Connect via: ssh vpsuser@$TAILSCALE_IP"

      - name: Maintain Connection
        run: |
          # ⬅️ CHANGE: Using simple bash loop to keep the runner active
          echo -e "\n=== VPS (SSH) ACCESS INFO ==="
          echo "Address: $TAILSCALE_IP"
          echo "Username: vpsuser"
          # The password is in the RDP_CREDS variable
          echo "Password: $(echo $RDP_CREDS | awk '{print $NF}')" 
          echo "=============================\n"
          
          # Keep runner active indefinitely (or until manually cancelled)
          while true; do
              echo "[$(date)] VPS Active - Use Ctrl+C in workflow to terminate"
              sleep 300
          done
