name: VPS

on:
  workflow_dispatch:

jobs:
  secure-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Create VPS User with Secure Password
        run: |
          password=$(LC_ALL=C tr -dc 'A-Za-z0-9!@#$%^&*()_+=-' < /dev/urandom | head -c 16)
          username="vpsuser"
          
          sudo useradd -m -s /bin/bash $username
          echo "$username:$password" | sudo chpasswd
          
          sudo usermod -aG sudo $username
          
          echo "RDP_CREDS=User: $username | Password: $password" >> $GITHUB_ENV
          
          if ! id -u $username > /dev/null 2>&1; then
              echo "User creation failed"
              exit 1
          fi

      - name: Configure SSH and Firewall
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          
          sudo sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          
          sudo service ssh restart
          
          sudo ufw allow 22/tcp

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sudo sh

      - name: Establish Tailscale Connection
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$GITHUB_RUN_ID
          
          tsIP=""
          retries=0
          while [ -z "$tsIP" ] && [ $retries -lt 10 ]; do
              tsIP=$(sudo tailscale ip -4)
              sleep 5
              retries=$((retries+1))
          done
          
          if [ -z "$tsIP" ]; then
              echo "Tailscale IP not assigned. Exiting."
              exit 1
          fi
          echo "TAILSCALE_IP=$tsIP" >> $GITHUB_ENV

      - name: Verify SSH Accessibility
        run: |
          echo "Tailscale IP: $TAILSCALE_IP"
          
          if ! timeout 5 bash -c "</dev/tcp/$TAILSCALE_IP/22"; then
              echo "TCP connection to SSH port 22 failed"
              exit 1
          fi
          echo "SSH connectivity successful! Connect via: ssh vpsuser@$TAILSCALE_IP"

      - name: Maintain Connection
        run: |
          echo -e "\n=== VPS (SSH) ACCESS INFO ==="
          echo "Address: $TAILSCALE_IP"
          echo "Username: vpsuser"
          echo "Password: $(echo $RDP_CREDS | awk '{print $NF}')" 
          echo "=============================\n"
          
          while true; do
              echo "[$(date)] VPS Active - Use Ctrl+C in workflow to terminate"
              sleep 300
          done
